version: 2

multi-ecosystem-groups:
  tauri-app-updates:
    schedule:
      interval: "weekly"

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      action-updates:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/src-tauri"
    multi-ecosystem-group: "tauri-app-updates"
    patterns:
      - "*"

  - package-ecosystem: "bun"
    directory: "/"
    multi-ecosystem-group: "tauri-app-updates"
    patterns:
      - "*"